### ISSUE TITLE
Yaml error.

### ISSUE THREAD

**Issue by FUZIK** [tim740/skUtilities#9]
spigot: buildtools, 1.11.2
skript: ben2.2-dev23
skutilities: 0.8.8
-------------
yml.sk:
```
command yml:
	trigger:
		set {_temp::*} to yaml nodes "" from file "plugins\Skript\scripts\yml"
		loop {_temp::*}:
			broadcast "%yaml value ""%loop-value%.int"" from file ""plugins\Skript\scripts\yml""%"
```
yml:
```
example1:
  int: 101
example2:
  int: 010
example3:
  int: 101
```
error:
```
Invalid brackets/variables/text in 'yaml value "' (yml.sk, line 5: 
'broadcast "%yaml value ""%loop-value%.int"" from file ""plugins\Skript\scripts\yml""%"')
```
